### ISSUE TITLE
Folder Picker `maxSelectable: 1` gives the appearance of allowing multiple selections

### ISSUE THREAD

**Issue by cgrdavies** [box/box-ui-elements#1705] opened 2019-11-04 16:40 UTC
**Environment:**

- Elements version: latest

**Desktop (please complete the following information):**

- OS: [e.g. Windows 10] macOS 10.14
- Browser [e.g. chrome, safari] Chrome and Safari

**Steps to reproduce the problem:**

Forked version of the official folder picker codepen with `maxSelectable` set to `1`: https://codepen.io/box-platform/pen/WRQLey

1) select `A Sample Folder`
2) navigate to `An Ordered Folder`
3) navigate back to the parent folder
4) select `An Ordered Folder`

Check marks appear next to both `A Sample Folder` and `An Ordered Folder` but Selected Items shows 1 selection. When the selection is saved, the last folder selected is passed to the client (i.e. the behavior is correct, but appearance of the picker is out of sync). 

**What is the expected behavior? (Screenshots can be helpful here)**

When `maxSelectable = 1`, a check mark only appears next to one folder at a time. 

**What went wrong? (Screenshots, console logs, or HAR files can be helpful here)**

Nothing logged in console.

**Additional context**

We are using the bundled JS/CSS assets, rather than the react components directly. 

Animated GIF of the issue on codepen: 

![bug](https://user-images.githubusercontent.com/4152264/68139335-f3130d00-fef7-11e9-8314-7e8ce708af97.gif)

**Comment by cgrdavies** [comment] 2019-11-05 12:50
I tracked down the source of this problem and, in the end, it was fairly obvious once I looked over the implementation. 

[This line](https://github.com/box/box-ui-elements/blob/master/src/elements/content-picker/ContentPicker.js#L818) depends on the contents of `selected` being a reference to an object within `currentCollection`. However, when you navigate between folders and the collection is reloaded from the API, that reference is broken, so the `selected: true` on the prior selection is never cleaned up. 

@priyajeet (tagging you since you last touched this specific aspect of the component): would you be open to a PR that filtered the `currentCollection` by `id` and removed the `selected` from the matching prior item?

**Comment by priyajeet** [comment] 2019-11-05 18:20
@mickr Can this be fixed as part of your maxSelectable: 1 changes?

**Comment by mickr** [comment] 2019-11-05 18:51
@priyajeet the `maxSelectable` changes have been merged.

**Comment by sahiga** [comment] 2020-04-02 19:28
@cgrdavies I'm not able to reproduce this issue with the latest CDN release (https://cdn01.boxcdn.net/platform/elements/11.0.2/en-US/picker.js). In v11.0.2, we released the fix from #1685, which replaces the checkboxes with single-select radio buttons when `maxSelectable = 1`.

Can you try upgrading to v11.0.2 and let us know if you're still seeing this issue?

**Closed** 2022-07-05 22:02 UTC
