### ISSUE TITLE
Box Content Picker overwrites button styles of Bootstrap 4

### ISSUE THREAD

**Issue by Helveg** [box/box-ui-elements#673] opened 2018-12-02 14:53 UTC
**Environment:**
- Elements version: 7.2.0

**Steps to reproduce the problem:**
1. Include `https://cdn01.boxcdn.net/platform/elements/7.2.0/nl-NL/picker.css` as stylesheet
2. Include `https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css`

**What is the expected behavior? (Screenshots can be helpful here)**
I expect the buttons of the content picker to have one style, and the default Bootstrap buttons to have their own style.

![image](https://user-images.githubusercontent.com/28923979/49341193-64906e80-f64a-11e8-9c4e-5d23a4dbafa0.png)

**What went wrong? (Screenshots, console logs, or HAR files can be helpful here)**
The style of other buttons on my page, not inside of the Box UI Elements is overridden.

![image](https://user-images.githubusercontent.com/28923979/49341180-1aa78880-f64a-11e8-985a-fb15fe9a3ac9.png)

**Comment by DanDeMicco** [comment] 2018-12-03 18:10
Duplicate of #522. Unfortunately, it is a problem with our underlying component library which has the same css classes as bootstrap. We are aware of the issue, and hopefully it will be resolved soon

**Comment by tmswartz12** [comment] 2019-12-04 21:33
Any update on this? Having the same issue and am hoping to fix it!!

**Comment by sahiga** [comment] 2019-12-05 18:25
Hi @tmswartz12 and @Helveg, thanks for reaching out about this issue!

We recently created a new **next** dist tag with namespaced CSS class names, e.g., `bdl-Button` instead of `btn`. You can see the changes in [this commit](https://github.com/box/box-ui-elements/commit/86e1e14d3fb6cde5ea83e6e6b3ee60923d536918). If you're using npm, you can upgrade to [11.0.0-next.1](https://github.com/box/box-ui-elements/releases/tag/v11.0.0-next.1%40next) to try out the new class names.

Please note that this release is **experimental** and thus will not be available via our CDN. If you find any bugs, please report them to us in this thread.

**Comment by dylandamsma** [comment] 2022-08-27 15:26
Hi there, 2022 still experiencing this issue with version 15.0.0

This CSS still contains the `.btn` & `.btn-primary` classes, overwriting or clashing with tailwind classes in my app: https://cdn01.boxcdn.net/platform/elements/15.0.0/en-US/explorer.css

How to fix this?

**Comment by dtrodger** [comment] 2023-10-12 15:20
We're also running into this. Can this please get fixed?

**Closed** 2024-04-09 18:39 UTC
Labels: investigation
