### ISSUE TITLE
User that uploaded the document does not show up on UI Content Explorer

### ISSUE THREAD

**Issue by mremigio** [box/box-ui-elements#198] opened 2018-03-03 00:25 UTC
Hello:

I wrote issue #193 and I am grateful for a response, but, the response does not answer my question.
So I am going to ask again.  Sorry, just need an answer.

When a user uploads a document through the UI Content Explorer, the name of the user that uploaded the document does not seem to show up.  Only the uploaded date shows up.
Is there an option that I can set so that the user's name shows up.  If an option is currently not available, is there a plan to add it ?

Thanks

Mila

**Comment by tonyjin** [comment] 2018-03-03 00:31
Dupe of #193. Please do not re-file issues multiple times. We can see comments in closed tickets and will re-open them if appropriate.

**Closed by tonyjin** 2018-03-03 00:31 UTC
