### ISSUE TITLE
On UI Explorer, how do I configure it to show the person that uploaded the document

### ISSUE THREAD

**Issue by mremigio** [box/box-ui-elements#197] opened 2018-03-02 16:33 UTC
We are using the UI Content Explorer, but, the person that uploaded the document does not show up on the list of documents that were uploaded.  How can we achieve this ?

Here's our code:
 
 var folderId = '0';
 var accessToken = '6UGMm8CkfB5AK0ao2sycdYRqeP0jUsrT';
 var contentExplorer = new Box.ContentExplorer();
 contentExplorer.show(folderId, accessToken, {
                container: '.container'
  });

**Comment by tonyjin** [comment] 2018-03-02 22:12
Dupe of https://github.com/box/box-ui-elements/issues/193

**Closed by tonyjin** 2018-03-02 22:12 UTC
